definitions:
  handler.Response:
    properties:
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      password:
        type: string
    type: object
info:
  contact: {}
paths:
  /user/users:
    get:
      description: Get all users
      operationId: FindAll
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/handler.Response'
            type: array
      security:
      - ApiKeyAuth: []
      summary: Get all users
      tags:
      - users
swagger: "2.0"
